### ISSUE TITLE
Warning: Each child in a list should have a unique "key" prop.

### ISSUE THREAD

**Issue by jjunCoder** [limi-chory/scratch-map-app#2]
```
Warning: Each child in a list should have a unique "key" prop.
Check the render method of `Map`. See https://reactjs.org/link/warning-keys for more information.
    at Map (http://localhost:3000/static/js/bundle.js:108:100)
    at App
```
단순 warning. key 를 안쓴듯? 근데 위에 콘솔로그 살펴보면 `    at Map (http://localhost:3000/static/js/bundle.js:108:100)` 이게 도움이 안되는데 타입스크립트가 컴파일된 자바스크립트의 위치를 찍어주는건가? 이럴땐 오류가 나는 위치가 어딘지 콘솔로그보고 어떻게 파악함?

**Comment by limi-chory** [comment]
React-Typescript를 js로 컴파일한 부분에서 위치를 찍어준게 맞음.
그래서 저거는 at Map 보고 그냥 컴포넌트 위치만 파악하고 해결해야 되는거같은데,
오류 보고 컴포넌트 내에서 어디쯤인지 파악해야되는듯..!! 
[#39b32af](https://github.com/limi-chory/scratch-map-app/commit/39b32afb332dff3a2792f50d0db4290e2a89ff01) 에서 수정해뒀어
